fix git-run-staged

diff --git a/bin/git-run-staged b/bin/git-run-staged
--- a/bin/git-run-staged
+++ b/bin/git-run-staged
@@ -1,4 +1,4 @@
-#!/bin/sh -e
+#!/bin/bash
 
 verbose=0
 
@@ -52,13 +52,17 @@ echo '--------------------------------------------------------------'
 echo '---- Stash all unstaged/untracked files (git stash -k -u) ----'
 echo '--------------------------------------------------------------'
 [ $verbose = 1 ] && set -x
-BEFORE_STASH_HASH=$(git rev-parse refs/stash || echo "")
+if ! BEFORE_STASH_HASH=$(git rev-parse --quiet refs/stash 2>/dev/null); then
+    BEFORE_STASH_HASH=$(git rev-parse HEAD)
+fi
 git stash -k -u
 AFTER_STASH_HASH=$(git rev-parse refs/stash)
 set +x
-if [ "$BEFORE_STASH_HASH" == "$AFTER_STASH_HASH" ]; then
-  echo -e '\n\n---- Stash failed! Please check and retry. ----\n\n';
-  exit 1;
+if [ "$BEFORE_STASH_HASH" = "$AFTER_STASH_HASH" ]; then
+    echo '-----------------------------------------------'
+    echo '---- Stash failed! Please check and retry. ----';
+    echo '-----------------------------------------------'
+    exit 1;
 fi;
 
 # run test only with staged files
@@ -67,10 +71,12 @@ echo '---- Run tests ----'
 echo '-------------------'
 set +e # don't exit on command failure
 [ $verbose = 1 ] && set -x
-/bin/bash -c "$@"
+$SHELL -c "$@"
 exitcode=$?
 if ! [ $exitcode = "0" ]; then
-    echo -e '\n\n---- Tests failed! Please fix it before commit. ----\n\n'
+    echo '----------------------------------------------------'
+    echo '---- Tests failed! Please fix it before commit. ----'
+    echo '----------------------------------------------------'
 fi
 
 # restore all stashed changes
@@ -80,7 +86,7 @@ echo '-----------------------------------------------------------'
 echo '---- Restore all stashed files (git stash pop --index) ----'
 echo '-----------------------------------------------------------'
 [ $verbose = 1 ] && set -x
-git reset --hard -q \
+(git reset --hard -q \
     && git clean -df -q \
-    && git stash pop --index -q \
-    || (echo -e '\n\n---- Restore failed! Please check and fix it. ----\n\n')
+    && git stash pop --index -q) \
+    || (echo '---- Restore failed! Please check and fix it. ----')
